export const analysisRoute = '/analysis'
export const connectionsRoute = '/analysis/connections'
export const plausibilityRoute = '/analysis/plausibility'
export const extractionRoute = '/analysis/extraction'
export const proposalsRoute = '/proposals'
export const codexRoute = '/codice'
